#!/usr/bin/env bash
#
#3 ./src/create_lat_lon_file alacranes
isla=${1}
{ echo -e "lat,lon"; } > ${isla}_lat_lon_file.csv
./src/create_lat_and_lon_data_file ${isla}
pr -mts, ${isla}_lat_coordinates.csv ${isla}_lon_coordinates.csv >> ${isla}_lat_lon_file.csv
